---
- name: Error handling
  hosts: appServers
  tasks:
   - block:
      - name: Install httpd1
         yum:
           name: httpd1
           state: present
         rescue:
         - name: Install httpd
           apt:
           name: httpd
           state: absent
         always:
         - name: Check url response
           uri:
           url: "{{item}}"
         with_items:
         - http://13.234.76.141
         - http://65.1.148.81

